In [90]:
#1
import pandas as pd
data = {
    "name":["Nate","Jhon", "Jane","Mandy"],
    "age":[39,23,31,25],
    "sex":["m", "m", "f","f"],
    "email":["nate@gmail.com","john@gmail.com", "jane@gmail.com", "mandy@gmail.com"],
    "phurchases":[34, 12, 42, 8]
    }

df = pd.DataFrame(data=data)
df

    name  age sex            email  phurchases
0   Nate   39   m   nate@gmail.com          34
1   Jhon   23   m   john@gmail.com          12
2   Jane   31   f   jane@gmail.com          42
3  Mandy   25   f  mandy@gmail.com           8

In [91]:
#2
df = df.rename(columns={"sex":"gender"})
df

    name  age gender            email  phurchases
0   Nate   39      m   nate@gmail.com          34
1   Jhon   23      m   john@gmail.com          12
2   Jane   31      f   jane@gmail.com          42
3  Mandy   25      f  mandy@gmail.com           8

In [92]:
#3

df["active"]=True

In [93]:
#4
df.loc[:,["name","email"]]

    name            email
0   Nate   nate@gmail.com
1   Jhon   john@gmail.com
2   Jane   jane@gmail.com
3  Mandy  mandy@gmail.com

In [95]:
#5
df["phurchases"].add(5)

0    39
1    17
2    47
3    13
Name: phurchases, dtype: int64

In [96]:
#6

df[df["phurchases"]>20]

   name  age gender           email  phurchases  active
0  Nate   39      m  nate@gmail.com          34    True
2  Jane   31      f  jane@gmail.com          42    True

In [97]:
#7

df["gender"]=df["gender"].replace({"m":"male", "f":"female"})
df

    name  age  gender            email  phurchases  active
0   Nate   39    male   nate@gmail.com          34    True
1   Jhon   23    male   john@gmail.com          12    True
2   Jane   31  female   jane@gmail.com          42    True
3  Mandy   25  female  mandy@gmail.com           8    True